"""Sunday-evening planning pass: run the strategy pod, then write each proposal
as a markdown file under `proposals/YYYY-MM-DD/` plus a one-page MONDAY_BRIEF.md
summary the operator (or a remote routine) reads first thing Monday.

This wrapper is **git-agnostic**. It only writes files. The caller (local cron,
the remote Sunday routine, or the operator running it by hand) is responsible
for committing and pushing.

Behavior on missing API key
---------------------------
If `ANTHROPIC_API_KEY` is empty AND `OKR_MONITOR_DRY_RUN` is unset, this script
flips dry-run on for the duration of this run and adds a clear banner to
MONDAY_BRIEF.md so the operator can see at a glance that the proposals are
stubs. This makes the wrapper safe to run in environments (like a remote
sandbox) where the secret may not be available — it never silently bills 0
calls and it never crashes for a missing key.

Usage
-----
  python scripts/sunday_evening.py
  python scripts/sunday_evening.py --date 2026-05-03   # backfill / dry runs
  OKR_MONITOR_DRY_RUN=true python scripts/sunday_evening.py
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import traceback
from datetime import date
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv
    load_dotenv(ROOT / ".env")
except ImportError:
    pass

from agents.ceo import pipeline as ceo_pipe  # noqa: E402
from agents.cpo import pipeline as cpo_pipe  # noqa: E402
from agents.cto import pipeline as cto_pipe  # noqa: E402
from agents.cfo import pipeline as cfo_pipe  # noqa: E402
from core import store  # noqa: E402


_AGENTS = [
    ("ceo", ceo_pipe),
    ("cpo", cpo_pipe),
    ("cto", cto_pipe),
    ("cfo", cfo_pipe),
]


def _force_dry_run_if_no_key() -> bool:
    """Returns True iff this run forced dry-run because no API key was
    available. Caller uses this to add a banner to the brief."""
    if os.environ.get("OKR_MONITOR_DRY_RUN", "").lower() in ("true", "false"):
        return False
    if os.environ.get("ANTHROPIC_API_KEY"):
        return False
    os.environ["OKR_MONITOR_DRY_RUN"] = "true"
    return True


def _run_pod(today: date) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for name, mod in _AGENTS:
        try:
            stats = mod.run(today=today)
            results.append({"agent": name, "ok": True, "stats": stats})
        except Exception as exc:
            results.append({
                "agent": name, "ok": False,
                "error": str(exc), "trace": traceback.format_exc(),
            })
    return results


def _fetch_proposal_for_run(run_id: str) -> dict[str, Any] | None:
    with store.connect() as conn:
        row = conn.execute(
            "SELECT id, agent, kind, title, summary, body_md, confidence, model"
            " FROM proposals WHERE run_id = ? ORDER BY created_at DESC LIMIT 1",
            (run_id,),
        ).fetchone()
    return dict(row) if row else None


def _write_proposal_files(out_dir: Path, results: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """For each successful agent, fetch its proposal from the DB and write
    `<agent>_<kind>.md`. Returns the list of {row, path} dicts in the order
    agents ran."""
    written: list[dict[str, Any]] = []
    for r in results:
        if not r.get("ok"):
            continue
        run_id = r["stats"].get("run_id")
        if not run_id:
            continue
        row = _fetch_proposal_for_run(run_id)
        if not row:
            continue
        path = out_dir / f"{row['agent']}_{row['kind']}.md"
        path.write_text(row["body_md"], encoding="utf-8")
        written.append({"row": row, "path": path})
    return written


def _build_monday_brief(
    *,
    today: date,
    written: list[dict[str, Any]],
    failures: list[dict[str, Any]],
    forced_dry_run: bool,
) -> str:
    lines: list[str] = [
        f"# Monday Brief — week starting {today.isoformat()}",
        "",
        f"_Generated by the strategy pod on {today.isoformat()}._",
        "",
    ]
    if forced_dry_run:
        lines.extend([
            "> ⚠️ **Dry-run mode** — `ANTHROPIC_API_KEY` was not available in this environment.",
            "> The proposals below are stubs from `core/llm._default_mock()`, not real model output.",
            "> Surface this to the routine config so the next Sunday brief is real.",
            "",
        ])
    lines.extend([
        f"**{len(written)} proposal(s)** are in the queue. "
        f"Review locally with: `python -m cli.review --all`.",
        "",
        "## This week's proposals",
        "",
    ])
    for item in written:
        row, path = item["row"], item["path"]
        conf = row["confidence"]
        conf_s = f"{conf:.2f}" if conf is not None else "—"
        rel = path.relative_to(ROOT).as_posix()
        lines.append(f"### {row['agent'].upper()} · {row['kind']}  ·  confidence {conf_s}")
        lines.append(f"**{row['title']}**")
        lines.append("")
        lines.append((row["summary"] or "").strip())
        lines.append("")
        lines.append(f"_Full proposal:_ [`{rel}`](../{path.parent.name}/{path.name})")
        lines.append("")

    if failures:
        lines.append("## Agents that failed this run")
        lines.append("")
        for f in failures:
            lines.append(f"- **{f['agent']}**: `{f.get('error', 'unknown error')}`")
        lines.append("")
        lines.append("_See `data/audit/<today>.jsonl` for full traces._")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## What to do Monday morning",
        "",
        "1. `python -m cli.review --all` — walk the queue, decide on each proposal.",
        "2. Update `TRACKER.md` §6 (Sprint Log) and §7 (Decision Log) with anything you accept.",
        "3. If any proposal called for a TRACKER.md change, edit and commit.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--date",
        type=date.fromisoformat,
        default=None,
        help="Override 'today' for backfill or testing. ISO format YYYY-MM-DD.",
    )
    args = parser.parse_args()
    today = args.date or date.today()

    forced_dry_run = _force_dry_run_if_no_key()

    out_dir = ROOT / "proposals" / today.isoformat()
    out_dir.mkdir(parents=True, exist_ok=True)

    store.init_db()
    results = _run_pod(today)
    written = _write_proposal_files(out_dir, results)
    failures = [r for r in results if not r.get("ok")]

    brief_md = _build_monday_brief(
        today=today, written=written, failures=failures,
        forced_dry_run=forced_dry_run,
    )
    brief_path = out_dir / "MONDAY_BRIEF.md"
    brief_path.write_text(brief_md, encoding="utf-8")

    summary = {
        "today": today.isoformat(),
        "out_dir": out_dir.relative_to(ROOT).as_posix(),
        "brief_path": brief_path.relative_to(ROOT).as_posix(),
        "proposals_written": [
            {"agent": w["row"]["agent"],
             "kind": w["row"]["kind"],
             "path": w["path"].relative_to(ROOT).as_posix(),
             "confidence": w["row"]["confidence"]}
            for w in written
        ],
        "failures": [{"agent": f["agent"], "error": f.get("error")} for f in failures],
        "forced_dry_run": forced_dry_run,
    }
    print(json.dumps(summary, indent=2, default=str))
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
